# Introduction to Julia

## Programming Basics

### Comments
There are two ways to write a comment:
* \# for single lined comments
* #= \
    commment \
    =# for multi lined comments

In [1]:
# This is a single lined comment and will not be run by Julia

#=
This is a 
multi lined comment
and also will not
be run
=# 

Although not technically a comment, since it is run by Julia, one can also write docstrings. This is used to explain parts of the code and create a documentation.

In [2]:
"""
Docstrings are usually
writen before a function with
an explanation of what it does
so that later it appears in the 
documentation.
"""

"Docstrings are usually\nwriten before a function with\nan explanation of what it does\nso that later it appears in the \ndocumentation.\n"

### Loops

Loops are useful when we want to repeat a piece of code several times.
There are two types of loops:
* For loops, repeat the code as many times as iterations specified.
* While loops, repeat the code until a given condition is fulfilled.

In [3]:
# For loop
for i in 1:10 # Also works as in Matlab --> for i=1:10
    println("Iteration number ", i)
end

# While loop
n = 1
while n <= 10
    println("Iteration number ", n)
    n += 1 # n = n + 1
end

Iteration number 1
Iteration number 2
Iteration number 3
Iteration number 4
Iteration number 5
Iteration number 6
Iteration number 7
Iteration number 8
Iteration number 9
Iteration number 10
Iteration number 1
Iteration number 2
Iteration number 3
Iteration number 4
Iteration number 5
Iteration number 6
Iteration number 7
Iteration number 8
Iteration number 9
Iteration number 10


### If-statements

If-statements allow to run a part of the code only if a cetain condition holds.

In [4]:
# Simple if-statement
a = 0
b = 1

if a < b
    println("a is smaller than b")
end

# If-statement with an alternative in case that the condition does not hold
c = 2
d = 3

if c == d
    println("c is equal to d")
else
    println("c is not equal to d")
end

# Multi If-statements
if c == d
    println("c is equal to d")
elseif c > d
    println("c is bigger than d")
else
    println("c is neither equal nor bigger than d, so it must be smaller")
end

# If-statement with several conditions
if a < b && c < d
    println("Both conditions hold")
end

if a < b || c > d
   println("At least one of the two conditions holds") 
end

a is smaller than b
c is not equal to c 
c is neither equal nor bigger than d, so it must be smaller
Both conditions hold
At least one of the two conditions holds


### Print to the Output window

There are several ways to show the output of a variable in Julia. The most common ones are:
* print()
* println(): Similar to print() but it introduces a line at the end
* display(): Useful for arrays and other objects where an instructive description of the object itself might be important to know.

In [5]:
A = ones(4,4)

print(A) # There will not be any jump of line between this and the following print/display
println(A) # It will generate an end of the line, allowing the following print/display to be in a different line.
display(A)

[1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0][1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]


4×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

### Functions

Functions are used to repeat program code with different arguments.

Contrary to how Matlab functions work, in Julia one does not need to create a different file for the function to be in. Moreover, if the function is in a different file, this one does not need to be named exactly the same as the function it stores.

In [ ]:
function f(x)
    return x^2
end

# Anonymous function
h(x) = x^2
g = x -> x^2 # This is an alternative way of creating an anonymous function

println(f(2))
println(h(2))
println(g(2))

4
4
4


### Structures

Structures in Julia are a bit more complex than in Matlab.
Without any other external packages, Julia structures are inmutable. This means that once defined, the structure cannot be modified. This is not a problem in Matlab since we can change a variable inside a structure any time. However, the package "Setfield" allows us to get the same functionality from Julia structures.

In [7]:
# Option 1
par1 = (x=1.0, y=2.0)

# Option 2: using a constructor (i.e. a function that creates new objects from structures)
using Parameters
@with_kw struct XandY
    x = 1.0
    y = 2.0
end
par2 = XandY()

println(par1.x)
println(par2.x)

# Now we want to change x = 2.0 in par2
using Setfield

@set! par2.x = 2.0

println(par2.x)

# @ are what is called a Macro. In this course we are not going to cover it but anyone interested can check the following beginers
# introduction:
# https://jkrumbiegel.com/pages/2021-06-07-macros-for-beginners/

1.0
1.0
2.0


## Generating Vectors and Matrices

Julia is very similar to Matlab in that vectors and matrices are defined in square brackets. Nevertheless, there are some slight differences which one has to pay attention to.

In [7]:
# Row vector of size 1x3
rvec = [1 2 3] 

# Column vector of size 3x1
cvec = [1 2 3]' # This is different to Matlab cvec = [1; 2; 3]

# One dimensional array (defined as size(n,1))
# Not possible in Matlab
vec1 = [1; 2; 3]
# or
vec2 = [1, 2, 3]

# vec3 = vec2 * vec1

# Matrix of size 2x2
Mat = [1 2; 3 4]

# Check Type
typeof(Mat)  # It tells you what kind of element is that variable 
eltype(Mat)  # It tells you what kind of elements does the variable contain

# typeof() and eltype() give the same result for scalar variables

Float64

There are some other special matrices and vectors which can be generated by using build in (or from third party packages) functions. Examples are:
* zeros(rows,cols)
* ones(rows,cols)
* rand(rows,cols) and randn(rows,cols)
* etc.

In [9]:
# Matrix of zeros
Mat = zeros(2,2) # 2x2
Mat = zeros(3,3) # 3x3
Mat = zeros(4,2) # 4x2

# Matrix of ones
Mat = ones(2,2) # Same as with zeros()

# Identity matrix, requires the library "LinearAlgebra"
using LinearAlgebra

Imat = I # In Matlab Mat = eye(rows,cols)  
# The size will be determined by the other matrices with which
# we do operations.

# Matrix of uniform random numbers
Mat = rand(2,2)

# Matrix of normally distributed random numbers
Mat = randn(2,2)

2×2 Matrix{Float64}:
 -1.31802  -0.0131159
 -1.39378  -1.28202

## Sequences

In Julia, sequences are a 1D arrays of size(n,)

In [10]:
# Generates a sequence from 1 to 10 with steps of size 1
seq = 1:1:10

# Sequence/Vector of 10 linearly spaced points between 1 and 3
seq = range(1,3,length = 10) # In Matlab this is done with
                             # linspace(1,3,10)

1.0:0.2222222222222222:3.0

## Accessing Vector/Matrix Elements

In [11]:
A = [1 2 3; 4 5 6; 7 8 9]

A[1,2]       # Select element row = 1 and column = 2
A[1:2, :]    # Selects the first 2 rows and all the columns
A[:, 1:2]    # Selects the all rows and first 2 the columns
A[[1, 3], :] # Selects rows 1 and 3 and all the columns
diag(A)      # Extracts the diagonal elements of matrix A

3-element Vector{Int64}:
 1
 5
 9

## Mathematical Operations

The mathematical operators in Julia follow the rules of matrix calculus. 

Thus if $A = \begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}\\
\end{bmatrix}$ and $B = \begin{bmatrix}
b_{11} & b_{12}\\
b_{21} & b_{22}\\
\end{bmatrix}$, then matrix multiplication yields,

$A * B = \begin{bmatrix}
a_{11} * b_{11} + a_{21} * b_{12} & a_{12} * b_{11} + a_{22} * b_{12}\\
a_{11} * b_{21} + a_{21} * b_{22} & a_{12} * b_{21} + a_{22} * b_{22}\\
\end{bmatrix}$

If one wants to calculate
$\begin{bmatrix}
a_{11} * b_{11} & a_{12} * b_{12}\\
a_{21} * b_{21} & a_{22} * b_{22}\\
\end{bmatrix}$, then we need to carry **element-wise** multiplication.

In [12]:
A = [1 2; 3 4]
B = [1 2; 3 4]
n = 2

# Basic operators
AplusB  = A + B # Addition
AminusB = A - B # Substraction
AtimesB = A * B # Matrix multiplication
AdivB   = A / B # Matrix division (B has to be invertible)
Apowern = A^n   # Exponentiation --> A^2 = A*A

# Element-wise operators
AplusB  = A .+ B
AminusB = A .- B 
AtimesB = A .* B # Element-wise Multiplication
AdivB   = A ./ B # Element-wise Division
Apowern = A .^ n # [a11^2 a12^2; a21^2 a22^2]

# Other
# This four are equivalent. The last two options are the most recommended in order to take the inverse of a matrix.
BdivA = B * inv(A)
BdivA = B * A^(-1)
BdivA = B / A
BdivA = A \ B

detA     = det(A)   # Calculated the determinant of A
val, vec = eigen(A) # Obtains the eingenvalues and eigenvectors of A
normA    = norm(A)  # Obtains the euclidean norm of A
invA     = inv(A)   # Calculates the inverse of A
pinvA    = pinv(A)  # Calculates the pseudo-inverse of A
rankA    = rank(A)  # Obtains the rank of A
diagA    = diag(A)  # Extract only the diagonal elements of A

2-element Vector{Int64}:
 1
 4

## Other matrix operations

In [13]:
A = [1 2; 3 4]

# Sum rows/columns
sum(A, dims = 1) # Sums over all rows. If A is 2x2 it will output a 1x2 matrix, with the only row being the sum of all the previous ones.
sum(A, dims = 2) # Sums over all rows. If A is 2x2 it will output a 2x1 matrix, with the only column being the sum of all the previous ones.
sum(A)           # It sums all the matrix. If A is 2x2 it will output a scalar

# Cumulative sum
cumsum(A, dims = 1) # Along rows
cumsum(A, dims = 2) # Along columns

# Search for the maximum
maximum(A, dims = 1) # It will search the maximum along the rows
maximum(A, dims = 2) # It will search the maximum along the columns
maximum(A)           # It will search for the maximum in the entire matrix

# Search for the mimimum
minimum(A, dims = 1)
minimum(A, dims = 2)
minimum(A)

1

## Vector and Matrix manipulation

In [14]:
A = [1 2; 3 4]

AT = A' # Transpose
Bh = [[1 2] [1 2]] # Horizontal Concatenation
Bv = [[1 2]; [1 2]] # Vertical Concatenation

Ashape = reshape(A, 1, 4) # Reshape Matrix A to be 1x4
Avec   = A[:]             # Converts matrix into a vector

Alr = reverse(A, dims = 2) # Flips the matrix left to right
Aud = reverse(A, dims = 1) # Flips the matrix updown

Arep = repeat(A, 2, 3) # Repeats the matrix 2 times in the row dimension and 3 times in the column dimension (Same as repmat() in Matlab)

4×6 Matrix{Int64}:
 1  2  1  2  1  2
 3  4  3  4  3  4
 1  2  1  2  1  2
 3  4  3  4  3  4

## Boolean Operators

For matrix and scalar comparison and we can use the following:
* == checks for equality
* != checks for inequality

Only for scalar comparison (or element-wise in matrices) we can use the following:
* \> checks whether left object is larger
* < checks whether left object is smaller
* \>= checks whether left object is greater or equal 
* <= checks whether left object is less or equal

For element-wise comparison just add . in front of the boolean operators (e.g. .>, .==, etc.).

The result of the relational operators is a logical variable (i.e. true = 1 and false = 0)

Other boolean operators are:
* && equivalent to "and"
* || equivalent to "or"

In [15]:
A = [1 2 3; 4 5 6; 7 8 9]
B = A
C = A.^2 - B

A == B # Output: true
A .== B # Output: true=1 for every element
A .< C  # Output: false=0 for a11 < c11 and a12 < c12, true=1 for the rest of elements

A[1,1] == B[1,1] && A[1,1] < C[1,1] # Output: false, because both have to be true (first condition is true but the second is false)
A[1,1] == B[1,1] || A[1,1] < C[1,1] # Output: true, because at least one condition is true
A == B && A != C                    # Output: true, since both conditions are true

# Errors: Operations not possible
A > B
A < B
A >= B
A <= B
A .== C && A .!= C
A .== C || A .!= C

LoadError: MethodError: no method matching isless(::Matrix{Int64}, ::Matrix{Int64})
Closest candidates are:
  isless(::Any, ::Missing) at missing.jl:88
  isless(::Missing, ::Any) at missing.jl:87

## Useful libraries
* **Plots**: plot, histogram, scatter
* **Statistics**: mean, std, cor, median, quantile
* **LinearAlgebra**: I, eigvals, eigvecs, det, cholesky
* **Distributions**: Normal, cdf, pdf
* **Random**: rand, randn
* **Parameters**: @with_kw
* **Roots**: fzero
* **CubicSplines**: CubicSpline
* **Interpolations**: interpolate
* **Optim**: optimize, minimizer, minimum
* etc.

## Additional Sources for learning Julia

https://docs.julialang.org/en/v1/

https://cheatsheets.quantecon.org/#manipulating-vectors-and-matrices

https://cheatsheet.juliadocs.org

https://www.youtube.com/user/JuliaLanguage/videos