# Problem 1
We start by learning some basic operations in python:

a) Open a new file or a new notebook and rename it accordingly.

b) Start your script by importing the NumPy library with command ``import numpy as np``.

**Example:**

In [45]:
# import library
import scipy as sp

In [47]:
# ... your code

c) Create an array of four zeros with command ``array1 = np.zeros(4)``.

**Example:**

NumPy arrays are the fundamental data structure used to represent collections of data in NumPy. There are several convenient ways to initialize an array, depending on the context.

In [50]:
import numpy as np
arr0 = np.zeros(10)
arr1 = np.ones(10)
arr2 = np.arange(10)
print(arr0)
print(arr1)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]


In [52]:
# ... your code

d) Transform this array into a vector with command ``array1.shape = (4, 1)``.

**Example**:

We can rearrange the data in a NumPy array into different shapes—such as vectors, matrices, or higher-dimensional tensors—by setting its ``shape`` attribute to a tuple specifying the desired dimensions. Alternatively, we can use the ``reshape`` method to create a new view of the array with the specified shape.

In [55]:
print(arr0) # just an array

arr0.shape = (1, 10) # a vector with 1 row and 10 columns
print(arr0)

arr0.shape = (5, 2) # a matrix with 5 rows and 2 columns
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [57]:
# ... your code

e) Transform this vector into a 2x2 matrix.

In [60]:
# ... your code

f) Create an array $A$ with
$$A=\begin{pmatrix} 1 & 2\\ 5 & 4\end{pmatrix}$$
Use ``np.array([[1, 2], [5, 4]])``.

**Example:**

You can also create a NumPy array by passing a native Python list (including nested lists for multidimensional arrays) to the ``np.array()`` constructor.

In [63]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
# ... your code

g) Determine the maximum in each row by using ``np.maximum()`` and the maximum element by using ``np.amax()``. Make sure to understand the differences between the two functions!

**Example:**

The function ``np.maximum()`` takes two arrays as arguments and returns an array containing the elementwise maximum of the two input arrays (see documentation: https://numpy.org/doc/2.2/reference/generated/numpy.maximum.html).

The function ``np.amax()`` returns the maximum value in an array. By specifying the ``axis`` argument, you can control the dimension along which the maximum is computed. In this case, ``np.amax()`` returns an array of maximum values along the specified ``axis``, rather than a single maximum value for the entire array (see documentation https://numpy.org/doc/stable/reference/generated/numpy.amax.html).

In [68]:
max0 = np.maximum(arr1, arr2) # take the elementwise maximum of arr1 and arr2
print(max0)

amax0 = np.amax(arr2) # find the maximum element of arr2
print(amax0)

arr2.shape = (5, 2) # reshape into a 5x2 matrix
print(arr2)

amax1 = np.amax(arr2, axis=0) # compare all the rows
print(amax1)

[1. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
9
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[8 9]


h) Construct the matrix $C$ as the inverse of $A$ by using ``np.linalg.inv()``.

**Example:**

The ``numpy.linalg`` module provides a wide range of linear algebra functions (see documentation: https://numpy.org/doc/stable/reference/routines.linalg.html). For example, ``np.linalg.inv()`` computes the inverse of a square matrix - that is, the matrix $A^{-1}$ such that $A^{-1}A = I$, where $I$ is the identity matrix.

In [71]:
mat0 = np.diag(np.ones(5)) * 5 # 5x5 matrix with value 5 along the diagonal
print(mat0)

mat0_inv = np.linalg.inv(mat0) # inverse
print(mat0_inv)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


In [73]:
# ... your code

i) Construct a column vector $b$ with
$$b=\begin{pmatrix} 1\\2\\3\end{pmatrix}$$
and multiply it by 2 using ``*``. Store the resulting vector as ``c``.

**Example:**

You can perform elementwise multiplication on NumPy arrays using the ``*`` operator. If the multiplier is a scalar, each element of the array is multiplied by that scalar (see the last example).

In [76]:
# ... your code

j) Construct the inner product, the outer product (by using operator @) and the Hadamard product (by using *) of the two vectors $b$ and $c$. The transpose of an array is generated by ``np.transpose()``.

**Example:**

Matrix products in NumPy are computed using the @ operator. Make sure the dimensions of the involved matrices or vectors are compatible for multiplication. You can compute the transpose of a matrix or vector using either ``np.transpose()`` or the ``.T`` attribute. The Hadamard product (elementwise multiplication) is performed with the ``*`` operator, as shown in the previous example. For inner and outer products, ensure you apply the appropriate transpose to the vectors involved.

In [83]:
mat0 = np.array([[2, 3], [4, 5]]) # 2x2 matrix
mat1 = np.array([[2, 3], [4, 5], [6, 7]]) # 3x2 matrix
mat2 = np.array([[0, 1], [2, 3]]) # another 2x2 matrix

mat_prod = mat0 @ mat1.T # transpose mat1 otherwise there is a dimension missmatch
print(mat_prod)

had_prod = mat0 * mat2
print(had_prod)

[[13 23 33]
 [23 41 59]]
[[ 0  3]
 [ 8 15]]


In [85]:
# ... your code

k) The function ``range()`` is especially important when using for-loops. Construct a for-loop with syntax ``for i in range()`` and simply ``print(i)``. Get yourself acquainted with this function, run a loop forward until a specific number, e.g. 10, and then backwards.

**Example:**

The ``range()`` function returns a sequence of numbers, starting from 0 by default, incrementing by 1, and stopping before a specified number. Its syntax is ``range(start, stop, step)``. A for loop then iterates over the sequence generated by ``range()``. The running variable ``i`` can be used inside the loop for more advanced purposes.

In [92]:
# for-loop 1
for i in range(10):
    print(i)

# for-loop 2
for j in range(10, 5, -2):
    print(j)

0
1
2
3
4
5
6
7
8
9
10
8
6


In [94]:
# ... your code