## Problem 2

In this exercise, we want to write some small functions on our own. Functions in Python are initialized by command ``def`` followed by the name of the function, function arguments in parantheses and a colon (:), e.g.: ``def function_name(arg):`` Additionally, the command ``return`` indicates the objects that should be returned to the calling code.

**Example:**

The code below defines a function called ``myFunction`` that takes one argument, prints the argument, and returns a variable ``x``. Once the function is defined, it can be called elsewhere in the code.

In [8]:
# define myFunction
def myFunction(arg0):
    # print the input argument arg0
    print(arg0)

    # create a variable x
    x = 10

    # return the value of x
    return x

# use myFunction in the code
value = 15
y = myFunction(value)
print(y)

15
10


a) Write a function that determines the maximum of the absolute difference between two given arrays. Use ``np.abs()``.

**Example:**

``np.abs()`` computes the absolute value of its input.

In [13]:
import numpy as np

var0 = -10
var1 = 30

abs0 = np.abs(var0)
abs1 = np.abs(var1)

print(abs0)
print(abs1)

10
30


In [15]:
# ... your code

b) Use the arrays $b$ and $c$ from Exercise 1 to test your function.

In [18]:
# ... your code

c) Write a function ``util`` that, given scalar inputs ``x`` and ``sigma``, is of the following form:
$$\text{util}(x, \sigma) = \frac{x^{1-\sigma}-1}{1-\sigma} \quad \text{if} \quad x>0.$$
Moreover, assign a large negative number in case ``x`` not positive. The syntax of an ``if/else`` statement in Python is given by

``if expression 1:``

``   statement1``

``elif expression 2:``

``   statement2``

``else:``

``   statement3``

**Example:**

In addition to the ``if/else`` syntax (see the example below), you can compute powers in Python using either the ``**`` operator or the NumPy function ``np.power()``.

In [32]:
a = 2**2
b = np.power(2, 2)

print(a)
print(b)

if a == b:
    print('same value!')
else:
    print('not the same value!')

4
4
same value!


In [34]:
# ... your code

d) Choose $\sigma=2$ and generate an array with entries $[-1, 3, -5, 10]$ as input. First, check element-by-element if your function works. Then, try to use the whole array as an input. If you get an error message, think about a way around.

**Example 1:**

You can access individual elements of an array by specifying their indices using square brackets. To extract entire sequences, you can use slicing with the colon (:) operator.

In [40]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

print(array[0]) # access entries using the index
print(array[3])

print(array[:]) # access multiple entries using slicing
print(array[2:5])

1
4
[1 2 3 4 5 6 7]
[3 4 5]


**Example 2:**

You can evaluate multiple boolean expressions at once, but the if statement handles only one condition at a time. To solve part (d), try to avoid using if statements by introducing an indicator function instead.

In [49]:
indicator0 = array > 3
print(indicator0)

print(indicator0 * 5) # False = 0, True = 1

[False False False  True  True  True  True]
[0 0 0 5 5 5 5]


In [51]:
# ... your code