# Notebook zu Potenzenmethode & Rayleigh-Quotienten-Iteration

In [2]:
import numpy as np
import scipy.linalg as spla

Wir betrachten die Matrizen
$$
A = \begin{pmatrix} 5 & 4 & 4 & 5 \\ 9 & 4 & 8 & 3 \\ -9 & -4 & -8 & -5 \\ 0 & 1 & 1 & 2 \end{pmatrix} \qquad \text{und} \qquad
B = \begin{pmatrix} 5 & 4 & 4 & 5 \\ 6 & 4 & 5 & 3 \\ -6 & -4 & -5 & -5 \\ 0 & 1 & 1 & 2 \end{pmatrix}.
$$
Anhand dieser Matrizen wollen wir die Verfahren zur Approximation von Eigenwerten testen und verstehen. 

**(a) Um die Ergebnisse der Verfahren später beurteilen zu können, lassen Sie sich von Python zunächst die "korrekten" Eigenwerte berechnen und anzeigen. Benutzen Sie dazu den Befehl `eig` aus dem `linalg` Modul von `scipy`. Da dieses Modul oben mit dem Namen `spla` eingebunden wurden, wird der Befehl also über `spla.eig(...)` aufgerufen.**

In [3]:
A = np.array([[5.0, 4, 4, 5],[9, 4, 8, 3],[-9, -4, -8, -5],[0, 1, 1, 2]])
B = np.array([[5.0, 4, 4, 5],[6, 4, 5, 3],[-6, -4, -5, -5],[0, 1, 1, 2]])
print(A)
print(B)

[[ 5.  4.  4.  5.]
 [ 9.  4.  8.  3.]
 [-9. -4. -8. -5.]
 [ 0.  1.  1.  2.]]
[[ 5.  4.  4.  5.]
 [ 6.  4.  5.  3.]
 [-6. -4. -5. -5.]
 [ 0.  1.  1.  2.]]


In [4]:
lamA,vA = spla.eig(A)
print('Eigenwerte von A:')
print(lamA)

lamB,vB = spla.eig(B)
print('Eigenwerte von B:')
print(lamB)

Eigenwerte von A:
[ 5.+0.j -4.+0.j  1.+1.j  1.-1.j]
Eigenwerte von B:
[ 5.+0.j -1.+0.j  1.+1.j  1.-1.j]


## Potenzenmethode

**(b) Schreiben Sie eine Prozedur, die `K` Iterationen der Potenzenmethode für eine Matrix `A` und einen Startvektor `z0` berechnet. Die Prozedur soll die aktuelle Approximation an den Eigenwert in jedem Schritt auf dem Bildschirm ausgeben, und am Ende die finale Approximationen an den Eigenwert und den Eigenvektor an das Hauptprogramm zurückgeben.**

**Hinweis:** Das komplexe Skalarprodukt $x^H y = \overline{x}^T y$ zweier Vektoren $x$ und $y$ erhalten Sie in numpy durch `np.vdot(x,y)`.

Außerdem ein kleiner Tipp, _falls_ Sie an einer schönen Bildschrimausgabe interessiert sind: In sogenannten "F-Strings" können Sie die Darstellung von Zahlen in Strings (also z.B. für den `print`-Befehl) beeinflussen. Ein Beispiel:

In [5]:
a = np.sqrt(2) 
print('Die Variable hat den Wert',a)
print(f'Die Variable hat den Wert {a:.3f}')

Die Variable hat den Wert 1.4142135623730951
Die Variable hat den Wert 1.414


In der zweiten Variante wurde die Darstellung der in `a` gespeicherten Zahl spezifiziert. Das führende `f` vor dem String erlaubt solche Formatierungen. Die geschweiften Klammern stellen einen Platzhalter für eine Zahl, die formatiert ausgegeben werden soll, dar. Vor dem Doppelpunkt wird angegeben, welche Variable ausgegeben werden soll, und dahinter wird spezifiziert in welcher Darstellung. Das `f` steht für eine Fix point number (das Komma trennt also immer den ganzahligen Teil von dem Rest). Der Zusatz `.3` legt genauer fest, dass 3 Nachkommastellen nach dem Dezimalpunkt angezeigt werden sollen.

In [6]:
def power_iteration(A, z0, K):
    y = z0/spla.norm(z0)

    for k in range(K):
        z = A @ y
        q = np.vdot(y, z)
        y = z/spla.norm(z)

        print(f'Schritt {k+1:2d}: q = {q:.4f}')
                
    return q, y

**(c) Testen Sie die Prozedur mit den obigen Matrizen $A$ und $B$. Starten Sie dabei mit einem beliebigen Vektor, z.B. $z_0 = (1,1,1,1)^T$, und berechnen Sie 30 Iterationen. Gegen welchen Eigenwert von $A$ bzw. $B$ konvergiert die Methode, und warum? Vergleichen und erklären Sie die Konvergenzgeschwindigkeiten. Überprüfen Sie außerdem den Fehler der finalen Approximationen $\lambda,v$ an Eigenwert und Eigenvektor, indem Sie den Wert von $\left\lVert Av-\lambda v \right\rVert_2$ für die jeweilige Matrix ausgeben.**

In [7]:
print('Matrix A:')
z0 = np.ones([4,1])
(eigvalue, eigvector) = power_iteration(A, z0,30)

print("\nFehler in der EW-EV-Gleichung:", spla.norm(A @ eigvector - eigvalue * eigvector))

Matrix A:
Schritt  1: q = 5.0000
Schritt  2: q = 3.2462
Schritt  3: q = 7.0396
Schritt  4: q = 3.6039
Schritt  5: q = 6.2713
Schritt  6: q = 4.0716
Schritt  7: q = 5.8163
Schritt  8: q = 4.3941
Schritt  9: q = 5.5165
Schritt 10: q = 4.6067
Schritt 11: q = 5.3277
Schritt 12: q = 4.7461
Schritt 13: q = 5.2085
Schritt 14: q = 4.8366
Schritt 15: q = 5.1329
Schritt 16: q = 4.8951
Schritt 17: q = 5.0848
Schritt 18: q = 4.9327
Schritt 19: q = 5.0542
Schritt 20: q = 4.9569
Schritt 21: q = 5.0347
Schritt 22: q = 4.9724
Schritt 23: q = 5.0222
Schritt 24: q = 4.9823
Schritt 25: q = 5.0142
Schritt 26: q = 4.9887
Schritt 27: q = 5.0091
Schritt 28: q = 4.9927
Schritt 29: q = 5.0058
Schritt 30: q = 4.9954

Fehler in der EW-EV-Gleichung: 0.008759265540775565


In [8]:
print('Matrix B:')
z0 = np.ones([4,1])
(eigvalue, eigvector) = power_iteration(B, z0,30)

print("\nFehler in der EW-EV-Gleichung:", spla.norm(B @ eigvector - eigvalue * eigvector))

Matrix B:
Schritt  1: q = 5.0000
Schritt  2: q = 5.1842
Schritt  3: q = 5.1431
Schritt  4: q = 4.9625
Schritt  5: q = 4.9888
Schritt  6: q = 4.9953
Schritt  7: q = 4.9997
Schritt  8: q = 5.0001
Schritt  9: q = 5.0001
Schritt 10: q = 5.0000
Schritt 11: q = 5.0000
Schritt 12: q = 5.0000
Schritt 13: q = 5.0000
Schritt 14: q = 5.0000
Schritt 15: q = 5.0000
Schritt 16: q = 5.0000
Schritt 17: q = 5.0000
Schritt 18: q = 5.0000
Schritt 19: q = 5.0000
Schritt 20: q = 5.0000
Schritt 21: q = 5.0000
Schritt 22: q = 5.0000
Schritt 23: q = 5.0000
Schritt 24: q = 5.0000
Schritt 25: q = 5.0000
Schritt 26: q = 5.0000
Schritt 27: q = 5.0000
Schritt 28: q = 5.0000
Schritt 29: q = 5.0000
Schritt 30: q = 5.0000

Fehler in der EW-EV-Gleichung: 4.2150232613335755e-15


## Inverse Potenzenmethode mit Shift

**(d) Schreiben Sie nun eine Prozedur, welche einen zusätzlichen Eingabeparameter $\mu$ hat und die inverse Potenzenmethode mit Shift $\mu$ durchführt.**

Zur Lösung der auftretenden LGS verwenden wir eine LR-Zerlegung. Für eine Matrix $A$ erhalten Sie diese über den Befehl, `spla.lu(A)`, welcher drei Matrizen $P,L,R$ (Permutationsmatrix, untere und obere Dreiecksmatrix) zurückgibt, für die $A = PLR$ gilt. ACHTUNG: Aus der VL kennen wir die Zerlegung in der Form $PA=LR$!

Mit dem Befehl `solve_triangular(A,b,lower=True)` bzw. `solve_triangular(A,b,lower=False)` können Sie dann LGS mit einer unteren/oberen Dreiecksmatrix durch Vorwärts- bzw. Rückwärtssubstitution lösen lassen.

In [9]:
def power_shift(A, z0, K, mu):
    y = z0/spla.norm(z0)
    
    N = A.shape[0]
    P, L, R = spla.lu(mu * np.eye(N) - A)
    for k in range(K):
        y = spla.solve_triangular(L, P.T@y, lower=True)
        z = spla.solve_triangular(R, y, lower=False)
        y = z / spla.norm(z)

        q = np.vdot(y, A@y)

        print(f'Schritt {k+1:2d}: q = {q:.4f}')
    
    return q, y    

**(e) Testen Sie Ihre Prozedur wie oben mit der Matrix $A$. Verwenden Sie als Shift zunächst $\mu = 4$. Was beobachten Sie im Vergleich zu oben? Verwenden Sie anschließend die Shifts $\mu = -3$ und $\mu = 0$. Was passiert und warum?**


In [37]:
mu = 2+2j

z0 = np.ones([4,1])
(eigvalue, eigvector) = power_shift(A, z0, 30, mu)

print("\nFehler in der EW-EV-Gleichung:", spla.norm(A @ eigvector - eigvalue * eigvector))

Schritt  1: q = 2.0785+1.9476j
Schritt  2: q = 1.8174+0.4440j
Schritt  3: q = 0.8772+0.6238j
Schritt  4: q = 0.9227+1.1021j
Schritt  5: q = 1.0490+1.0243j
Schritt  6: q = 1.0064+0.9798j
Schritt  7: q = 0.9918+0.9993j
Schritt  8: q = 1.0004+1.0032j
Schritt  9: q = 1.0012+0.9996j
Schritt 10: q = 0.9998+0.9996j
Schritt 11: q = 0.9998+1.0001j
Schritt 12: q = 1.0001+1.0000j
Schritt 13: q = 1.0000+1.0000j
Schritt 14: q = 1.0000+1.0000j
Schritt 15: q = 1.0000+1.0000j
Schritt 16: q = 1.0000+1.0000j
Schritt 17: q = 1.0000+1.0000j
Schritt 18: q = 1.0000+1.0000j
Schritt 19: q = 1.0000+1.0000j
Schritt 20: q = 1.0000+1.0000j
Schritt 21: q = 1.0000+1.0000j
Schritt 22: q = 1.0000+1.0000j
Schritt 23: q = 1.0000+1.0000j
Schritt 24: q = 1.0000+1.0000j
Schritt 25: q = 1.0000+1.0000j
Schritt 26: q = 1.0000+1.0000j
Schritt 27: q = 1.0000+1.0000j
Schritt 28: q = 1.0000+1.0000j
Schritt 29: q = 1.0000+1.0000j
Schritt 30: q = 1.0000+1.0000j

Fehler in der EW-EV-Gleichung: 6.197458969752588e-11


## Rayleigh-Quotienten-Iteration

**(f) Kopieren Sie Ihre Prozedur aus Teil (d) und ändern Sie diese zur Rayleigh-Quotienten-Iteration ab. Testen Sie diese wie in Teil (e). Verwenden Sie auch einmal einen besonders schlechten Shift, z.B. $\mu = 100$.**

Ggf. sollten Sie noch ein Abbruchkriterium ergänzen, z.B. falls $\left\lVert Av-\lambda v \right\rVert_2<10^{-14}$ für die aktuelle Approximation $\lambda,v$ an Eigenwert und Eigenvektor  gilt (sonst kann die Matrix $\mu I - A$ irgendwann singulär werden).

In [11]:
def rayleigh(A, z0, K, mu):
    y = z0/spla.norm(z0)
    
    N = A.shape[0]
    for k in range(K):
        P, L, R = spla.lu(mu * np.eye(N) - A)
        y = spla.solve_triangular(L, P.T@y, lower=True)
        z = spla.solve_triangular(R, y, lower=False)
        y = z / spla.norm(z)

        Ay = A@y
        q = np.vdot(y, Ay)
        mu = q

        if spla.norm(Ay - q*y) < 1e-14:
            return q, y
        
        print(f'Schritt {k+1:2d}: q = {q:.4f}')
    
    return q, y    

In [36]:
mu = 4

z0 = np.ones([4,1])
(eigvalue, eigvector) = rayleigh(A, z0, 30, mu)

print("\nFehler in der EW-EV-Gleichung:", spla.norm(A @ eigvector - eigvalue * eigvector))

Schritt  1: q = 4.0552
Schritt  2: q = 5.2725
Schritt  3: q = 5.0137
Schritt  4: q = 5.0000
Schritt  5: q = 5.0000

Fehler in der EW-EV-Gleichung: 7.691850746622416e-16
