---
# Tutoriumsblatt 4: Visualisierung passender Aufgaben
SS 2025 – Tutorium: Markovsche Ketten <br>
[Ilias Seite zum Kurs](https://ilias.studium.kit.edu/goto.php?target=crs_2640974&client_id=produktiv) <br>
Dominik Ebert

---

---
## T13 (Paintball)
---

SymPy: Python library for symbolic mathematics

Alternative: Mathematica, Maple, C

In [1]:
from sympy import symbols, Matrix, eye
from sympy import lambdify

import numpy as np

In [2]:
a, b, c = symbols('p_A p_B p_C')

In [3]:
P = Matrix(([(1 - a) * (1 - b) * (1 - c), 0, a * (1 - c) * (1 - b), (1 - a) * (c + b - b*c), 0, 0, a*(c + b - c*b), 0],
            [0, (1 - a) * (1 - b), 0, 0, a * (1 - b), b * (1 - a), 0, a*b],
            [0, 0, (1 - a) * (1 - c), 0 , a * (1 - c), 0, c * (1 - a), a*c],
            [0, 0, 0, (1 - b) * (1 - c), 0, b * (1 - c), c * (1 - b), b*c],
            [0, 0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 0],
            [0, 0, 0, 0, 0, 0, 0, 1]))

In [4]:
P

Matrix([
[(1 - p_A)*(1 - p_B)*(1 - p_C),                   0, p_A*(1 - p_B)*(1 - p_C), (1 - p_A)*(-p_B*p_C + p_B + p_C),             0,             0, p_A*(-p_B*p_C + p_B + p_C),       0],
[                            0, (1 - p_A)*(1 - p_B),                       0,                                0, p_A*(1 - p_B), p_B*(1 - p_A),                          0, p_A*p_B],
[                            0,                   0,     (1 - p_A)*(1 - p_C),                                0, p_A*(1 - p_C),             0,              p_C*(1 - p_A), p_A*p_C],
[                            0,                   0,                       0,              (1 - p_B)*(1 - p_C),             0, p_B*(1 - p_C),              p_C*(1 - p_B), p_B*p_C],
[                            0,                   0,                       0,                                0,             1,             0,                          0,       0],
[                            0,                   0,                       0,              

In [5]:
Q = P[:4, :4]
Q

Matrix([
[(1 - p_A)*(1 - p_B)*(1 - p_C),                   0, p_A*(1 - p_B)*(1 - p_C), (1 - p_A)*(-p_B*p_C + p_B + p_C)],
[                            0, (1 - p_A)*(1 - p_B),                       0,                                0],
[                            0,                   0,     (1 - p_A)*(1 - p_C),                                0],
[                            0,                   0,                       0,              (1 - p_B)*(1 - p_C)]])

In [6]:
R = P[:4, 4:]
R

Matrix([
[            0,             0, p_A*(-p_B*p_C + p_B + p_C),       0],
[p_A*(1 - p_B), p_B*(1 - p_A),                          0, p_A*p_B],
[p_A*(1 - p_C),             0,              p_C*(1 - p_A), p_A*p_C],
[            0, p_B*(1 - p_C),              p_C*(1 - p_B), p_B*p_C]])

In [7]:
M = (eye(4) - Q).inv() 
M

Matrix([
[1/(p_A*p_B*p_C - p_A*p_B - p_A*p_C + p_A - p_B*p_C + p_B + p_C),                        0, (-p_A*p_B*p_C + p_A*p_B + p_A*p_C - p_A)/(p_A**2*p_B*p_C**2 - 2*p_A**2*p_B*p_C + p_A**2*p_B - p_A**2*p_C**2 + 2*p_A**2*p_C - p_A**2 - 2*p_A*p_B*p_C**2 + 3*p_A*p_B*p_C - p_A*p_B + 2*p_A*p_C**2 - 2*p_A*p_C + p_B*p_C**2 - p_B*p_C - p_C**2), (1 - p_A)/(p_A*p_B*p_C - p_A*p_B - p_A*p_C + p_A - p_B*p_C + p_B + p_C)],
[                                                              0, 1/(-p_A*p_B + p_A + p_B),                                                                                                                                                                                                                                            0,                                                                       0],
[                                                              0,                        0,                                                                                            

In [8]:
U = M * R
U

Matrix([
[p_A*(1 - p_C)*(-p_A*p_B*p_C + p_A*p_B + p_A*p_C - p_A)/(p_A**2*p_B*p_C**2 - 2*p_A**2*p_B*p_C + p_A**2*p_B - p_A**2*p_C**2 + 2*p_A**2*p_C - p_A**2 - 2*p_A*p_B*p_C**2 + 3*p_A*p_B*p_C - p_A*p_B + 2*p_A*p_C**2 - 2*p_A*p_C + p_B*p_C**2 - p_B*p_C - p_C**2), p_B*(1 - p_A)*(1 - p_C)/(p_A*p_B*p_C - p_A*p_B - p_A*p_C + p_A - p_B*p_C + p_B + p_C), p_A*(-p_B*p_C + p_B + p_C)/(p_A*p_B*p_C - p_A*p_B - p_A*p_C + p_A - p_B*p_C + p_B + p_C) + p_C*(1 - p_A)*(1 - p_B)/(p_A*p_B*p_C - p_A*p_B - p_A*p_C + p_A - p_B*p_C + p_B + p_C) + p_C*(1 - p_A)*(-p_A*p_B*p_C + p_A*p_B + p_A*p_C - p_A)/(p_A**2*p_B*p_C**2 - 2*p_A**2*p_B*p_C + p_A**2*p_B - p_A**2*p_C**2 + 2*p_A**2*p_C - p_A**2 - 2*p_A*p_B*p_C**2 + 3*p_A*p_B*p_C - p_A*p_B + 2*p_A*p_C**2 - 2*p_A*p_C + p_B*p_C**2 - p_B*p_C - p_C**2), p_A*p_C*(-p_A*p_B*p_C + p_A*p_B + p_A*p_C - p_A)/(p_A**2*p_B*p_C**2 - 2*p_A**2*p_B*p_C + p_A**2*p_B - p_A**2*p_C**2 + 2*p_A**2*p_C - p_A**2 - 2*p_A*p_B*p_C**2 + 3*p_A*p_B*p_C - p_A*p_B + 2*p_A*p_C**2 - 2*p_A*p_C + p_B*p_

In [9]:
# Create a numpy function to evaluate U for given values of a,b,c
f = lambdify((a, b, c), U, 'numpy')

# Now we can plug in some values:
numeric_U = f(0.5, 0.5, 0.5)
print(np.array(numeric_U))

[[0.04761905 0.14285714 0.61904762 0.19047619]
 [0.33333333 0.33333333 0.         0.33333333]
 [0.33333333 0.         0.33333333 0.33333333]
 [0.         0.33333333 0.33333333 0.33333333]]
