# Numpy

Numpy ist ein grundlegendes Python-Modul für wissenschaftliche Berechnungen das sehr verbreitet eingesetzt wird.<br>
Viele weitere Module verwenden dieses Modul auch.

Wie immer binden wir das Modul mit `import` ein. Als Abkürzung hat sich np etabliert.

In [ ]:
import numpy as np

Jedes Modul definiert eine Variables `__version__` in der die Versionsnummer des Moduls steht.<br>
Dies ist, bei sich schnell entwickelnden Modulen, hilfreich um die passende Dokumentation zu lesen.

In [ ]:
np.__version__

## Numpy-Arrays
Die wichtigste Neuerung bei `Numpy` ist ein neuer Datentyp, das Numpy-Array (ndarray).<br>
Über die Funktion `np.array()` lassen sich Python-Listen in Numpy-Arrays umwandeln.

In [ ]:
a = np.array([1,2,3,4])
a

In [ ]:
type(a)

Im Gegensatz zu Python-Listen, enthalten Numpy-Arrays nur Elemente **eines** Datentyps.
Die anderen Elemente werden zur Not enstrechend umgewandelt.

In [ ]:
np.array([1,2,3.])  # Alle Elemente werden zu Fließkommazahlen umgewandelt.

In [ ]:
np.array([1,2,3.,'c']) # Alle Elemente werden zu Strings umgewandelt.

Analog zu der Python-Funktion `range()`  gibt es in Numpy eine Funktion `arange()` um direkt einen Numpy-Array zu generieren.

In [ ]:
b = np.arange(2,10,2)
b

Auch bei Numpy-Arrays kann man auf einzelne Elemente über den Index zugreifen.<br>
**Nicht vergessen:** Python zählt ab 0!

In [ ]:
b[2]

## Teilbereiche von Numpy-Arrays ("slices")
Man kann auch auf Teile des Arrays zugreifen. Dabei gibt man als Index Bereiche an.<br>
*name*[*start*:*stop*], auch hier ist *stop* wieder nicht Teil der Liste!

In [123]:
a

array([1, 2, 3, 4])

In [120]:
c = a[0:3]
c

array([1, 2, 3])

Läßt man den Startwert weg, wird beim 0ten Element begonnen.

In [ ]:
a[:3]

Läßt man den Stopwert weg, geht der Bereich bis zum Ende (inkl. letzem Element).

In [121]:
d = a[1:]
d

array([2, 3, 4])

Ist der obere Index negativ, so wird von hinten gezählt.
So bedeutet `-1` z.b. bis zum vorletzten Element (inklusiv).

In [124]:
a[:-1]

array([1, 2, 3])

## Mathematische Operatoren
Der große Vorteil von Numpy-Arrays ist ihr Verhalten unter numerischen Operationen.
Sie verhalten sich hier ähnlich wie Vektoren, die Operation wird auf alle Elemente parallel angewendet.<br>
Im Gegensatz zu den meisten Programmiersprachen, spart man dadurch viele Schleifen und erhält sehr übersichtlichen Programmtext.

In [ ]:
a

In [ ]:
a + 1

In [ ]:
print(a)
print(b)
a + b

In [ ]:
2*a

Allerdings gilt dies auch für die Multiplikation zweier Arrays, ],die auch elementweise durchgeführt wird.<br>
Hier hinkt der Vektorvergleich schon etwas.

In [ ]:
print(a)
print(b)
a * b

Will man statt elementweiser Multiplikation, das Skalarprodukt der Vektoren, so muss man die Funktion `np.dot()` verwenden.

In [ ]:
np.dot(a, b)

Analog gibt es mit `np.cross()` auch das Kreuzprodukt, allerdings ist dies nur in 2- und 3-Dimensionen definiert.

In [ ]:
np.cross(a, b)

In [ ]:
print(f'c={c} und d={d}')
print()
print("c x d =", np.cross(c, d))

Potenzieren funktioniert elementweise, wieder wie erwartet

In [ ]:
a**3

In [ ]:
a * a * a

## Weitere wichtige Funktionen:
Numpy implementiert auch eine Reihe weitere Funktionen, die einem die Programmierung leichter machen (und Schleifen ersparen).

So erhält man z.B. die Summe aller Elemente eine Numpy-Arrays mit der Funktion `np.sum()`,

In [ ]:
print(a)
print(np.sum(a))

und den Mittelwert mit `np.mean()`:

In [ ]:
np.mean(a)

Der Mittelwert ist natürlich die Summe der Elemente, geteilt durch die Anzahl der Elemente.
Letztere erhält man über die Python-Funktion len().

In [ ]:
np.sum(a) / len(a)

In [ ]:
len(a)

## Numpy-Arrays initialisieren

Neben `np.array()` und `np.arrange()` gibt es weitere Funktionen um Numpy-Arrays zu konstruieren:<br>
Will man einen Array bestimmter Größe bei dem alle Elemente den Wert `0` haben, kommt `np.zeros()` zum Einsatz.
Hier gebe ich nur an, wieviele Elemente der Array haben soll.

In [ ]:
np.zeros(10)

Analog kann ich auch einen Array nur mit dem Wert `1` über `np.ones()` erhalten.

In [ ]:
np.ones(10)

Für andere Zahlenwerte gibt es keine entsprechende Funktionen...

In [ ]:
np.twos(10)

... diese erhalte ich aber einfach über Multiplikation mit der entsprechenden Konstante.

In [ ]:
2 * np.ones(10)

### linspace()
Mit `np.linspace(*start*,*stop*,*num*)` gibt es eine weitere Funktion um Werte in einem Intervall zu erzeugen.<br>
Allerdings gibt man hier nicht wie bei `np.arange()` die Schrittweite, sondern die Anzahl (*num*) der Elemente an.<br>
**Wichtig**:`np.linspace()` ist eine der wenigen Funktionen, bei der die **obere Grenze Teil der Liste** ist!

In [ ]:
x = np.linspace(0, np.pi, 7)
print(x)

## Mathematische Funktionen
Alle Funktionen, die es im Modul `math` gibt, findet man auch in `numpy`.<br>
Praktische ist hier, dass auch diese dann elementweise berechnet werden:

In [ ]:
np.cos(x)

Wieder wird alles parallel berechnet und man spart die Programmierung von Schleifen.<br>
Besonders häufig verwendet man dies beim grafischen Darstellen von Funktionen, wie im nächsten Teil *matplotlib* gezeigt wird.